import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/styles/globals.scss";
import "react-toastify/dist/ReactToastify.css";
import { Header } from "@/widgets/header";
import { Providers } from "../providers/providers";
import { HeaderProfile } from "@/features/profile";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale} data-theme="light">
      <body className={montserrat.className}>
        <Providers>
          <Header profile={<HeaderProfile />} />
          {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
