import type { Metadata } from "next";
import "@/app/styles/globals.scss";
import { AppCookiesProvider } from "@/app/providers/app-cookies-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html>
      <body>
        <AppCookiesProvider>{children}</AppCookiesProvider>
      </body>
    </html>
  );
}
